// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *janela_principal;
#include <FL/Fl_BMP_Image.H>
extern Fl_BMP_Image *image;
#include <FL/Fl_Return_Button.H>
extern Fl_Return_Button *start;
#include <FL/Fl_Value_Input.H>
extern Fl_Value_Input *fmg;
extern Fl_Value_Input *populacao;
extern Fl_Value_Input *mutacao_inicial;

//####### Funcoes exportadas da GUI #########//

int gui_instantiate(void);

#endif
